# Generated by Django 4.1.5 on 2023-01-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_auto_20230102_2253"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
    ]
