# Generated by Django 4.1.5 on 2023-01-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="descrption",
            field=models.TextField(default="None"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
