# Generated by Django 4.1.5 on 2023-01-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_product_descrption_alter_product_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotion",
            old_name="description",
            new_name="descrption",
        ),
        migrations.RemoveField(
            model_name="product",
            name="descrption",
        ),
    ]
