# Generated by Django 4.1.5 on 2023-01-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_rename_description_promotion_descrption_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="promotion",
            old_name="descrption",
            new_name="description",
        ),
    ]
